### ISSUE TITLE
Adding cron jobs support  

### ISSUE THREAD

**Issue by omarkhairy21** [jplhomer/superflare#18]
Hey, @jplhomer thanks for that awesome work i was struggling to build my abstraction around the Cloudflare stack but you did an amazing job!

I am wondering if there is a plan to support Cron jobs. Also, i am ready to contribute to this.

**Comment by jplhomer** [comment]
I would love this!

- I would aim to design it like Laravel's [task scheduling](https://laravel.com/docs/10.x/scheduling#schedule-frequency-options) but probably with a smaller list of possible values
- The main value prop is that you don't have to reason about cron expressions at all to use it
- The dev would simply set the cron value in wrangler.json to run every minute, and Superflare's cron handler would attempt to match against the current date.

One challenge:

- Existing Cron expression parsers/matchers tend to be very heavy and rely on large 3p datetime deps. Would be great to find either a small one with no deps, or build our own modeled after e.g. https://github.com/datasert/cronjs

## Proposed API

```tsx
// worker.ts

export default {
  async scheduled(event: ScheduledEvent, env: Env, ctx: ExecutionContext) {
    await handleScheduled(event, env, ctx, (schedule: Schedule) => {
      schedule.run(async () => {
        // some bespoke function
      }).dailyAt('8:00').timezone('America/New_York');

      schedule.job(new MyJobClass(my, args))
        .weekly();

      // ...
    });
```

**Comment by jplhomer** [comment]
How does this sound? https://github.com/jplhomer/superflare/issues/18

**Comment by omarkhairy21** [comment]
Sounds Great! thanks for that huge effort I left a comment with just one concern on the pull request

**Comment by omarkhairy21** [comment]
BTW that pull request and your comment inspired me to create a [cron toolkit library](https://github.com/omarkhairy21/cron-toolkit-ts) to create cron expressions with human-readable functions also with type safety

**Comment by jplhomer** [comment]
@omarkhairy21 That's awesome!
