### ISSUE TITLE
New features / suggestions 

### ISSUE THREAD

**Issue by rodbs** [jplhomer/superflare#23]
It looks pretty awesome. Congratulations!
Some questions:  
 -Why are not using 'standard' Remix libraries like remix-auth  , zod ...?
 -Are you planning to integrate any testing library like playwright?
 -Why aren't you using CF Pages?
Thanks!

**Comment by jplhomer** [comment]
> -Why are not using 'standard' Remix libraries like remix-auth , zod ...?

I haven't used zod before, but I don't think it's necessarily a standard library — you could definitely use it if you wanted! I looked at Remix Auth, but it's tied to Remix (of course) and I wanted a very simple authentication solution that worked across frameworks.

> Are you planning to integrate any testing library like playwright?

I'm thinking about testing right now for sure. You could always add your own Playwright/Cypress E2E testing, but I also think it would be nice to:

- Have a "unit" test you can run against your models/jobs/etc with test data and assert that things work as expected
- Have an "integration" test where we use the [Miniflare vitest scaffolding](https://miniflare.dev/testing/vitest) and make actual HTTP request against the worker entrypoint
