### ISSUE TITLE
R2 documentation incorrect

### ISSUE THREAD

**Issue by blittle** [jplhomer/superflare#28]
The R2 documentation is incorrect. It says the API is `await storage().put(key, file);`, but in actuality it is `await storage().put(file);`. Though I wonder if there's a better API that could be provided for multipart uploads. I think the only way to work with the current API is to buffer an entire file upload into memory before saving to R2. Mixed with Remix, it looks like:

```ts
export async function action({request}: ActionArgs) {
  const uploadHandler = unstable_composeUploadHandlers(
    async ({ name, contentType, data, filename }) => {
      const dataArray1 = [];

      for await (const x of data) {
        dataArray1.push(x);
      }

      const file = new File(dataArray1, filename!, { type: contentType });

      await storage().put(file);

      return `${new URL(request.url).origin}/resources/images/${filename}`;
    }
  );

  const formData = await unstable_parseMultipartFormData(
    request,
    uploadHandler
  );

  const image = formData.get("image");

  return json({ image });
}
```

Is there another, better way to save files to r2 from multipart upload forms?

**Comment by blittle** [comment]
Looks like stream uploading works for me using `storage().putAs()`:

```ts
export async function action({ request}: ActionArgs) {
  const uploadHandler = unstable_composeUploadHandlers(
    async ({ name, contentType, data, filename }) => {
      let size = 0;

      const stream = new ReadableStream({
        async start(controller) {
          for await (const x of data) {
            size += x.length;
            if (size > 2097152) {
              // 2MB max size
              throw new Error("File too large");
            }

            controller.enqueue(x);
          }
          controller.close();
        },
      });

      const key = crypto.randomUUID();
      const r2storage = await storage().putAs(key, stream);
      return `${url.origin}/resources/images/${r2storage.key}`;
    }
  );

  try {
    const formData = await unstable_parseMultipartFormData(
      request,
      uploadHandler
    );

    const imageUrl = formData.get("image");

    return json({imageUrl});
  } catch (e) {
    return json({ error: (e as Error).message }, { status: 400 });
  }
}
```

**Comment by blittle** [comment]
Though the docs still need to be updated, so I'll keep this issue open.

**Comment by jplhomer** [comment]
@blittle I totally forgot about `putAs` 🙈 I probably meant that to be the signature `key, value` and not the other way around.

Here's a PR which rectifies that and introduces `putRandom` instead: https://github.com/jplhomer/superflare/pull/34

I also copied and modified Remix's `parseMultipartFormData` to make it super easy to upload a stream directly to R2.

lmk what you think?

Also: what's the 2MB limit you have in your example? Is that an R2 or CF Worker limit, or something you're imposing yourself?
