### ISSUE TITLE
Cannot open database because the directory doesn't exist

### ISSUE THREAD

**Issue by dan-gamble** [jplhomer/superflare#52]
I'm guessing this might be related to the [--experimental-backend](https://github.com/jplhomer/superflare/pull/49) D1 change but it appears the local path is different now for the sqlite database.

Looks to be now `.wrangler/state/v3/d1/[dbId]/db.sqlite`. Will open a PR attempting to sort this soon!

<img width="2056" alt="image" src="https://github.com/jplhomer/superflare/assets/7152041/9a9fe049-0926-468d-ab0a-bce2f2d411f1">

**Comment by jplhomer** [comment]
haha oh no - thank you!
